In [1]:
%matplotlib inline

In [20]:
import numpy as np
import librosa as lb
import matplotlib.pyplot as plt
import IPython.display as ipd
import scipy.io as sio
import warnings
from matplotlib.colors import LogNorm
import glob


In [21]:
warnings.filterwarnings(action='ignore') # to suppress warning messages

In [105]:
ipd.Audio("32834_denoised.mp3", rate = 16000)

In [30]:
def retrieveMP3s(indir):
    """
    Helper function to retrieve a list of all the .mp3 files listed in the provided directory
    
    Note: For macs, it's /*.mp3, for windows, it's \*.mp3
    
    """
    
    pathname = indir + '/*.mp3'
    
    return glob.glob(pathname)

In [31]:
queries = retrieveMP3s("Queries")

In [149]:
def getDigitTimes(queryName, hop_length = 128, top_db = 25):
    audio, sr = lb.core.load(queryName)
    digits = lb.effects.split(audio, hop_length = hop_length, top_db = top_db)
    
    return digits

In [146]:
def playDigits(queryName, digitTimes, hop_length=128, sr = 22050):
    
    audio, sr = lb.core.load(queryName)

    for time in digitTimes:
        ipd.display(ipd.Audio(audio[time[0]:time[1]], rate = sr))
    

In [154]:
test = getDigitTimes('denoisedQueries/73914130_denoised.mp3')

In [155]:
playDigits('denoisedQueries/73914130_denoised.mp3', test)

In [61]:
digitTime = []

for query in queries[0:5]:
    audio, sr = lb.core.load(query)
    digits = lb.effects.split(audio, hop_length = 128, top_db = 30)
    #np.append(digitTime, digits)
    digitTime.append([query, digits])
    #print(digits)

In [62]:
digitTime

[['Queries/1577.mp3', array([[  9088,  20096],
         [ 41600,  51968],
         [ 70784,  83200],
         [101120, 112512]])], ['Queries/77777.mp3', array([[ 10496,  21760],
         [ 47616,  60800],
         [ 84480,  91648],
         [ 92800,  96000],
         [125568, 135552],
         [162816, 174720]])], ['Queries/73914130.mp3', array([[  6656,  20864],
         [ 48512,  58112],
         [ 58496,  60544],
         [ 83840,  97024],
         [118016, 130944],
         [153216, 165632],
         [185216, 198784],
         [219520, 230144],
         [249984, 264320]])], ['Queries/4084782589.mp3',
  array([[ 10240,  19328],
         [ 44544,  57088],
         [ 82176,  88576],
         [ 90368,  91008],
         [ 91904,  92160],
         [ 94208,  95744],
         [120704, 131456],
         [155008, 168064],
         [193664, 200064],
         [229632, 239488],
         [267776, 279680],
         [305920, 312960],
         [339712, 353152]])], ['Queries/32834.mp3', array([[ 116

In [106]:
a = digitTime[4][1]

a = [i for i in a if (i[1] - i[0])/22050 > 0.35]
a

[array([16896, 30080]),
 array([46848, 59008]),
 array([79232, 87168]),
 array([111488, 123776]),
 array([143744, 159232])]